name: Build
on:
  push:

jobs:
  lnd:
    runs-on: ubuntu-latest
    env:
      GOPATH: /go
      GOVERSION: 1.15.6
      LND_COMMIT_ID: master
    container: reactnativecommunity/react-native-android:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          curl -LO https://golang.org/dl/go$GOVERSION.linux-amd64.tar.gz
          tar -C /usr/local -xzf go$GOVERSION.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin:/go/bin
          curl -LO https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
          unzip protoc-3.4.0-linux-x86_64.zip -d protoc
          export PATH=$PWD/protoc/bin:$PATH
          go get golang.org/x/mobile/cmd/gomobile
          gomobile init
          mkdir -p $GOPATH/src/github.com/lightningnetwork
          cd $GOPATH/src/github.com/lightningnetwork
          git clone https://github.com/lightningnetwork/lnd
          cd lnd
          git checkout $LND_COMMIT_ID
          mv -f $GITHUB_WORKSPACE/bindings.go mobile/bindings.go
          make android || make android
          cd mobile/build/android
      - name: upload AAR
        uses: actions/upload-artifact@v2
        with:
          name: Lndmobile.aar
          path: /go/src/github.com/lightningnetwork/lnd/mobile/build/android/Lndmobile.aar
